targets:
  $default:
    builders:
      flutter_gen:
        options:
          output: lib/gen/  # Generated code kahan save hoga
          line_length: 80   # Code formatting ke liye line length
          integrations:
            flutter_svg: true  # Flutter SVG package ke liye support